# Site settings
title: Alexander Bischof Github.io
email: alexanderxbischof@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alexander Bischof - Softwaredevelopment in the Java universe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexbischof.github.io" # the base hostname & protocol for your site
twitter_username: A_Bischof
github_username:  AlexBischof

# Build settings
markdown: kramdown
